import katex from 'katex';
import { multiplicationGrid, powers, primes } from './numbers.js';

const math = (source, displayMode = false) => katex.renderToString(source, { output: 'mathml', displayMode, throwOnError: true, strict: 'error' });
const inline = source => math(source);
const equation = source => `<div class="foundation-equation">${math(source, true)}</div>`;
const row = (id, title, formula, detail, kind = 'Identity') => ({ id, title, formula, detail, kind });
const table = (caption, headings, rows) => `<div class="foundation-table" tabindex="0" role="region" aria-label="${caption}"><table><caption>${caption}</caption><thead><tr>${headings.map(heading => `<th scope="col">${heading}</th>`).join('')}</tr></thead><tbody>${rows.map(cells => `<tr>${cells.map(cell => `<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;

export const sections = [
  { id: 'arithmetic', title: 'Arithmetic & number sense', note: 'The small facts that make larger ideas feel lighter.', items: [
    row('order', 'Order of operations', String.raw`2+3\times4=14`, 'Grouping first, then powers, then multiplication and division left to right, then addition and subtraction left to right. A fraction bar groups its numerator and denominator. Parentheses are kinder than ambiguous notation.', 'Convention'),
    row('fractions', 'Fractions: add, multiply, divide', String.raw`\frac ab+\frac cd=\frac{ad+bc}{bd}`, `${equation(String.raw`\frac ab\frac cd=\frac{ac}{bd},\qquad\frac{a/b}{c/d}=\frac{ad}{bc}`)}Denominators must be nonzero; division also requires ${inline(String.raw`c\ne0`)}. Use a common denominator for addition. Cancel common factors, not terms: ${inline(String.raw`\frac{a+b}{a}\ne 1+b`)} in general.`),
    row('percent', 'Ratios, percentages, and successive change', String.raw`p\%\text{ of }x=\frac{p}{100}x`, `A ratio compares quantities in compatible units. A 20% increase multiplies by 1.2; a 20% decrease multiplies by 0.8. Together they multiply by 0.96, not 1. Percentage change is ${inline(String.raw`100\frac{\mathrm{new}-\mathrm{old}}{\mathrm{old}}`)} for a positive old value.`, 'Rule'),
    row('gcd', 'Factors, gcd, and lcm', String.raw`\gcd(a,b)\operatorname{lcm}(a,b)=ab`, `For positive integers. Euclid's algorithm uses ${inline(String.raw`\gcd(a,b)=\gcd(b,a\bmod b)`)} until the remainder is zero. For 18 and 24: gcd = 6 and lcm = 72. Every integer greater than 1 has a unique prime factorization, apart from factor order.`, 'Theorem'),
    row('divisibility', 'Divisibility tests', '', 'By 2: last digit even. By 3 or 9: digit sum divisible by 3 or 9. By 4: last two digits divisible by 4. By 5: last digit 0 or 5. By 6: divisible by both 2 and 3. By 8: last three digits divisible by 8. By 10: last digit 0. By 11: alternating digit sum divisible by 11. These tests are for base-ten integers.', 'Rule'),
    row('progressions', 'Arithmetic and geometric progressions', String.raw`1+2+\cdots+n=\frac{n(n+1)}2`, `${equation(String.raw`\sum_{k=0}^{n-1}(a+kd)=\frac n2[2a+(n-1)d]`)}${equation(String.raw`\sum_{k=0}^{n-1}ar^k=a\frac{1-r^n}{1-r}`)}The geometric formula requires ${inline(String.raw`r\ne1`)}; for ${inline(String.raw`r=1`)} the sum is ${inline(String.raw`na`)}. The infinite sum is ${inline(String.raw`a/(1-r)`)} only when ${inline(String.raw`|r|<1`)}.`),
    row('modular', 'Remainders and modular arithmetic', String.raw`a\equiv b\pmod n`, `This means ${inline(String.raw`n`)} divides ${inline(String.raw`a-b`)}, with integer modulus ${inline(String.raw`n\ge2`)}. Addition and multiplication respect congruence. Division requires an inverse: ${inline(String.raw`a`)} has an inverse modulo ${inline(String.raw`n`)} exactly when ${inline(String.raw`\gcd(a,n)=1`)}. On a clock, ${inline(String.raw`10+5\equiv3\pmod{12}`)}.`, 'Definition'),
  ] },
  { id: 'number-tables', title: 'Numbers worth knowing', note: 'Patterns to recognize, not a test to pass.', items: [
    row('multiplication', 'Multiplication table: 1 through 20', '', `<div class="foundation-table multiplication-grid" tabindex="0" role="region" aria-label="Multiplication table, 1 through 20 times 1 through 10"><table><caption>Multiplication table, 1 through 20 times 1 through 10</caption><thead><tr><th aria-label="Multiply">&times;</th>${multiplicationGrid[0].map((_, index) => `<th scope="col">${index + 1}</th>`).join('')}</tr></thead><tbody>${multiplicationGrid.map((products, index) => `<tr><th scope="row">${index + 1}</th>${products.map(product => `<td>${product}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`, 'Table'),
    row('squares', 'Squares: 1 through 25', String.raw`25^2=625`, table('Squares up to 25 squared', ['n', 'n squared'], powers.map(entry => [entry.base, entry.square])) + `Consecutive squares differ by successive odd numbers: ${equation(String.raw`(n+1)^2-n^2=2n+1`)}`, 'Table'),
    row('primes', 'All primes up to 1000', '', `<p>A prime is an integer greater than 1 whose only positive divisors are 1 and itself. There are <strong>168</strong> here; 1 is not prime, and 2 is the only even prime.</p><ul class="prime-list">${primes.map(prime => `<li>${prime}</li>`).join('')}</ul><p>To test an integer, trial division only needs primes up to its square root. A composite number must have a factor no larger than its square root.</p>`, 'Table'),
  ] },
  { id: 'axioms', title: 'Axioms, logic & proof', note: 'What we assume, what we define, and what follows.', items: [
    row('axiom-identity', 'Axiom, definition, identity, theorem', '', 'An <strong>axiom</strong> or <strong>postulate</strong> is an assumption of a mathematical system. A <strong>definition</strong> gives a term its meaning. An <strong>identity</strong> is an equality valid for every allowed value. A <strong>theorem</strong> is proved from assumptions. The square and cube expansions below are identities, not axioms.', 'Language'),
    row('field', 'Real-number arithmetic: the field laws', String.raw`a(b+c)=ab+ac`, `${equation(String.raw`a+b=b+a,\qquad ab=ba`)}${equation(String.raw`(a+b)+c=a+(b+c)`)}${equation(String.raw`(ab)c=a(bc)`)}Addition and multiplication are associative and commutative. There are identities 0 and 1, additive inverses ${inline(String.raw`-a`)}, and multiplicative inverses ${inline(String.raw`1/a`)} for ${inline(String.raw`a\ne0`)}. Distributivity connects the two operations. These laws justify the algebraic expansions.`, 'Axioms'),
    row('order-completeness', 'Order and completeness of the real line', '', `Adding the same number preserves an inequality. Multiplying by a positive number preserves it; multiplying by a negative number reverses it. <strong>Completeness:</strong> every nonempty set of reals bounded above has a least upper bound. This is the property behind the real line having no rational-style gaps.`, 'Axioms'),
    row('euclid', "Euclid's postulates", '', 'In Euclidean geometry: a straight segment joins any two points; a segment can be extended straight; a circle can be drawn with any center and positive radius; all right angles are equal; and the parallel postulate holds. A familiar equivalent of the last: through a point not on a line, exactly one parallel line passes. Non-Euclidean geometries change that assumption, so triangle angle sums need not be 180 degrees.', 'Postulates'),
    row('induction', 'Mathematical induction', '', `Prove a base case. Then show that if the claim holds at ${inline(String.raw`n`)}, it holds at ${inline(String.raw`n+1`)}. Together these establish it for every integer from the base onward. Example: adding ${inline(String.raw`n+1`)} to ${inline(String.raw`n(n+1)/2`)} gives ${inline(String.raw`(n+1)(n+2)/2`)}, proving the sum formula's induction step.`, 'Proof method'),
    row('logic', 'Implication, quantifiers, and counterexamples', String.raw`(P\Rightarrow Q)\iff(\neg Q\Rightarrow\neg P)`, `An implication equals its contrapositive, not its converse. ${inline(String.raw`\forall`)} means "for every"; ${inline(String.raw`\exists`)} means "there exists." Negating "every" gives "there exists a counterexample": ${equation(String.raw`\neg(\forall x\ P(x))\iff\exists x\ \neg P(x)`)}A thousand confirming examples do not prove a universal claim; one counterexample refutes it.`, 'Logic'),
    row('sets', "Sets and De Morgan's laws", String.raw`(A\cup B)^c=A^c\cap B^c`, `${equation(String.raw`(A\cap B)^c=A^c\cup B^c`)}Complements are relative to a specified universe. "Not either" means "neither"; "not both" means "at least one is not." For finite sets, ${inline(String.raw`|A\cup B|=|A|+|B|-|A\cap B|`)}.`),
  ] },
  { id: 'algebra', title: 'Algebra & the binomial theorem', note: 'The same structure, written in a more useful way.', items: [
    row('square-sum', 'Square of a sum', String.raw`(a+b)^2=a^2+2ab+b^2`, `Expand ${inline(String.raw`(a+b)(a+b)`)} by distributivity. Two cross terms each contribute ${inline(String.raw`ab`)}. In the area model below, a square of side ${inline(String.raw`a+b`)} is divided into four rectangles.<figure class="square-figure"><canvas data-diagram="square" width="640" height="440" role="img" aria-label="A square divided into regions a squared, ab, ab, and b squared"></canvas><figcaption>Teal: a squared. Gold: the two ab rectangles. Rose: b squared.</figcaption><label>b <input type="range" min="1" max="4" step="0.5" value="2" data-square-size aria-label="Side length b"><output data-square-value>2</output></label></figure>`),
    row('square-difference', 'Square of a difference', String.raw`(a-b)^2=a^2-2ab+b^2`, `Replace ${inline(String.raw`b`)} with ${inline(String.raw`-b`)} in the square-of-a-sum identity. Example: ${inline(String.raw`99^2=(100-1)^2=10000-200+1=9801`)}.`),
    row('difference-squares', 'Difference of squares', String.raw`a^2-b^2=(a+b)(a-b)`, `The cross terms cancel. Example: ${inline(String.raw`103\times97=(100+3)(100-3)=10000-9=9991`)}. Over the reals, ${inline(String.raw`a^2+b^2`)} does not factor into ${inline(String.raw`(a+b)(a-b)`)}.`),
    row('cube-sum', 'Cube of a sum', String.raw`(a+b)^3=a^3+3a^2b+3ab^2+b^3`, `Multiply the square expansion by ${inline(String.raw`(a+b)`)} and collect terms. Coefficients 1, 3, 3, 1 count how many ways each product occurs.`),
    row('cube-difference', 'Cube of a difference', String.raw`(a-b)^3=a^3-3a^2b+3ab^2-b^3`, 'The signs alternate because odd powers of the negative term are negative.'),
    row('sum-difference-cubes', 'Sum and difference of cubes', String.raw`a^3-b^3=(a-b)(a^2+ab+b^2)`, `${equation(String.raw`a^3+b^3=(a+b)(a^2-ab+b^2)`)}Multiplying back is a quick way to check the middle sign.`),
    row('quadratic', 'Quadratic formula and completing the square', String.raw`ax^2+bx+c=0`, `${equation(String.raw`x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}`)}Requires ${inline(String.raw`a\ne0`)}. The discriminant ${inline(String.raw`b^2-4ac`)} distinguishes two real roots, one repeated real root, or two nonreal complex roots. Completing the square gives ${equation(String.raw`ax^2+bx+c=a\left(x+\frac b{2a}\right)^2+c-\frac{b^2}{4a}`)}The roots sum to ${inline(String.raw`-b/a`)} and multiply to ${inline(String.raw`c/a`)}.`, 'Formula'),
    row('binomial', 'The binomial theorem', String.raw`(a+b)^n=\sum_{k=0}^n\binom nk a^{n-k}b^k`, `For nonnegative integer ${inline(String.raw`n`)}. ${equation(String.raw`\binom nk=\frac{n!}{k!(n-k)!}`)}Choose which ${inline(String.raw`k`)} of the ${inline(String.raw`n`)} factors contribute ${inline(String.raw`b`)}. Pascal's triangle records these coefficients; each interior entry is the sum of the two above it.${table("Pascal's triangle", ['Power n', 'Coefficients'], [[0,'1'],[1,'1  1'],[2,'1  2  1'],[3,'1  3  3  1'],[4,'1  4  6  4  1'],[5,'1  5  10  10  5  1'],[6,'1  6  15  20  15  6  1']])}`, 'Theorem'),
    row('absolute', 'Absolute value and triangle inequality', String.raw`|a+b|\le|a|+|b|`, `Absolute value is distance from zero. ${inline(String.raw`|ab|=|a||b|`)} and ${inline(String.raw`\big||a|-|b|\big|\le|a-b|`)}. For ${inline(String.raw`r\ge0`)}, ${inline(String.raw`|x|\le r`)} means ${inline(String.raw`-r\le x\le r`)}.`, 'Inequality'),
  ] },
  { id: 'powers-logs', title: 'Powers, roots & logarithms', note: 'Multiplication becomes addition. Scale becomes distance.', items: [
    row('exponent-product', 'Multiply and divide powers', String.raw`a^m a^n=a^{m+n}`, `${equation(String.raw`\frac{a^m}{a^n}=a^{m-n}`)}The quotient requires ${inline(String.raw`a\ne0`)}. For arbitrary real exponents use ${inline(String.raw`a>0`)}; integer exponents also allow negative bases wherever defined. ${inline(String.raw`2^3\cdot2^4=2^7=128`)}.`),
    row('power-power', 'Powers of powers and products', String.raw`(a^m)^n=a^{mn}`, `${equation(String.raw`(ab)^n=a^nb^n,\qquad(a/b)^n=a^n/b^n`)}For real exponents take positive bases; the quotient needs a nonzero denominator. Integer-exponent laws extend more broadly. These laws do not extend blindly to principal complex powers.`),
    row('zero-negative', 'Zero, negative, and fractional exponents', String.raw`a^0=1,\qquad a^{-n}=\frac1{a^n}`, `Here ${inline(String.raw`a\ne0`)}. For ${inline(String.raw`a>0`)}, ${inline(String.raw`a^{m/n}=\sqrt[n]{a^m}`)} with integer ${inline(String.raw`n>0`)}. In real arithmetic ${inline(String.raw`\sqrt{a^2}=|a|`)}, not always ${inline(String.raw`a`)}. The expression ${inline(String.raw`0^0`)} needs a context-specific convention; it is not covered by the nonzero-base rule.`),
    row('log-definition', 'A logarithm asks for an exponent', String.raw`\log_b x=y\iff b^y=x`, `For real logarithms: ${inline(String.raw`x>0`)}, ${inline(String.raw`b>0`)}, ${inline(String.raw`b\ne1`)}. ${inline(String.raw`\ln x`)} uses base ${inline(String.raw`e`)}. ${inline(String.raw`\log_b1=0`)} and ${inline(String.raw`\log_b b=1`)}. The exponential and logarithm are inverse functions.<figure><canvas data-diagram="logs" width="720" height="440" role="img" aria-label="Exponential exp(x) and natural logarithm ln(x), reflected across the line y equals x"></canvas><figcaption>Teal: exp(x). Rose: ln(x). Dashed: y = x. Inverse functions exchange horizontal and vertical coordinates.</figcaption></figure>`, 'Definition'),
    row('log-laws', 'Products, quotients, and powers inside a log', String.raw`\log_b(xy)=\log_bx+\log_by`, `${equation(String.raw`\log_b(x/y)=\log_bx-\log_by`)}${equation(String.raw`\log_b(x^r)=r\log_bx`)}Use positive ${inline(String.raw`x,y`)} and a valid log base. There is no corresponding rule ${inline(String.raw`\log(x+y)=\log x+\log y`)}. A tenfold increase adds 1 to a base-ten logarithm.`),
    row('change-base', 'Change of base and exponential growth', String.raw`\log_bx=\frac{\ln x}{\ln b}`, `${equation(String.raw`a^x=e^{x\ln a}`)}For ${inline(String.raw`a>0`)}. Under ${inline(String.raw`N(t)=N_0e^{kt}`)}, doubling time is ${inline(String.raw`\ln2/k`)} for ${inline(String.raw`k>0`)}; half-life is ${inline(String.raw`-\ln2/k`)} for ${inline(String.raw`k<0`)}.`),
    row('logsumexp', 'Stable log-sum-exp', String.raw`\log\sum_i e^{z_i}=m+\log\sum_i e^{z_i-m}`, `Choose ${inline(String.raw`m=\max_i z_i`)} for finite real logits. The exponentials are then at most 1, avoiding overflow. Softmax is unchanged by a common shift because the common exponential factor cancels. Compute log-softmax as ${inline(String.raw`(z_i-m)-\log\sum_j e^{z_j-m}`)}, rather than taking the log of probabilities that may round to zero.`, 'Numerical method'),
  ] },
  { id: 'geometry', title: 'Geometry & measurement', note: 'Lengths, areas, and the shapes behind the symbols.', items: [
    row('angles', 'Angles, polygons, and similarity', String.raw`\pi\text{ radians}=180^\circ`, `A Euclidean triangle's interior angles sum to ${inline(String.raw`180^\circ`)}; a simple ${inline(String.raw`n`)}-gon's sum is ${inline(String.raw`(n-2)180^\circ`)}. Corresponding angles of similar triangles agree and corresponding side lengths have a common ratio. Scaling lengths by ${inline(String.raw`k>0`)} scales areas by ${inline(String.raw`k^2`)} and volumes by ${inline(String.raw`k^3`)}.`, 'Theorem'),
    row('pythagoras', "Pythagoras and the distance formula", String.raw`a^2+b^2=c^2`, `In a right triangle, ${inline(String.raw`c`)} is the hypotenuse. The converse holds for positive side lengths forming a triangle.${equation(String.raw`d=\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}`)}The midpoint is ${inline(String.raw`((x_1+x_2)/2,(y_1+y_2)/2)`)}.`, 'Theorem'),
    row('plane-areas', 'Areas of familiar shapes', '', table('Plane areas', ['Shape', 'Area'], [['Rectangle',inline(String.raw`wh`)],['Parallelogram',inline(String.raw`bh`)],['Triangle',inline(String.raw`bh/2`)],['Trapezoid',inline(String.raw`(a+b)h/2`)],['Circle',inline(String.raw`\pi r^2`)],['Ellipse',inline(String.raw`\pi ab`)]]) + 'Heights are perpendicular to the base. For a trapezoid, a and b are the parallel side lengths. For an ellipse, a and b are semiaxes.', 'Formulas'),
    row('circle', 'Circles: circumference, arcs, sectors', String.raw`C=2\pi r,\qquad A=\pi r^2`, `${equation(String.raw`s=r\theta,\qquad A_{\mathrm{sector}}=\frac12r^2\theta`)}The angle ${inline(String.raw`\theta`)} is in radians. A tangent is perpendicular to the radius at the point of contact. An inscribed angle subtending a fixed arc is half the corresponding central angle.`, 'Formulas'),
    row('solids', 'Volumes and surface areas', '', table('Solids', ['Solid', 'Volume', 'Total surface area'], [['Box',inline(String.raw`lwh`),inline(String.raw`2(lw+lh+wh)`)],['Sphere',inline(String.raw`4\pi r^3/3`),inline(String.raw`4\pi r^2`)],['Right cylinder',inline(String.raw`\pi r^2h`),inline(String.raw`2\pi r(h+r)`)],['Right circular cone',inline(String.raw`\pi r^2h/3`),inline(String.raw`\pi r(r+\ell)`)]]) + `For the cone, slant height ${inline(String.raw`\ell=\sqrt{r^2+h^2}`)}. A prism has volume base area times perpendicular height; a pyramid has one third of that. Units matter: area is square units, volume is cubic units.`, 'Formulas'),
    row('coordinate-lines', 'Lines and slopes', String.raw`y-y_0=m(x-x_0)`, `For a nonvertical line, ${inline(String.raw`m=(y_2-y_1)/(x_2-x_1)`)}. Parallel nonvertical lines have equal slopes; perpendicular lines with finite nonzero slopes satisfy ${inline(String.raw`m_1m_2=-1`)}. A vertical line is ${inline(String.raw`x=c`)}. The general form ${inline(String.raw`ax+by=c`)} includes both vertical and horizontal lines.`, 'Formulas'),
  ] },
  { id: 'trigonometry', title: 'Trigonometry', note: 'A circle quietly contains a world of waves.', items: [
    row('unit-circle', 'The unit circle and right-triangle ratios', String.raw`(x,y)=(\cos\theta,\sin\theta)`, `${equation(String.raw`\sin\theta=\frac{\mathrm{opposite}}{\mathrm{hypotenuse}},\quad\cos\theta=\frac{\mathrm{adjacent}}{\mathrm{hypotenuse}}`)}${equation(String.raw`\tan\theta=\frac{\sin\theta}{\cos\theta}`)}The triangle ratios apply to acute angles; the unit circle extends them to all real angles. Tangent requires ${inline(String.raw`\cos\theta\ne0`)}.`, 'Definition'),
    row('special-angles', 'Special angles worth remembering', '', table('Exact trigonometric values', ['Degrees', 'Radians', 'sin', 'cos', 'tan'], [[0,'0','0','1','0'],[30,inline(String.raw`\pi/6`),inline(String.raw`1/2`),inline(String.raw`\sqrt3/2`),inline(String.raw`1/\sqrt3`)],[45,inline(String.raw`\pi/4`),inline(String.raw`1/\sqrt2`),inline(String.raw`1/\sqrt2`),'1'],[60,inline(String.raw`\pi/3`),inline(String.raw`\sqrt3/2`),inline(String.raw`1/2`),inline(String.raw`\sqrt3`)],[90,inline(String.raw`\pi/2`),'1','0','Undefined']]) + 'Sine is positive above the horizontal axis; cosine to the right of the vertical axis. These signs extend the table to other quadrants.', 'Table'),
    row('trig-pythagorean', 'Pythagorean identities, symmetry, periodicity', String.raw`\sin^2\theta+\cos^2\theta=1`, `${equation(String.raw`1+\tan^2\theta=\sec^2\theta`)}The second identity needs ${inline(String.raw`\cos\theta\ne0`)}. Sine is odd; cosine is even. Sine and cosine have period ${inline(String.raw`2\pi`)}; tangent has period ${inline(String.raw`\pi`)}.`),
    row('angle-addition', 'Angle addition and double angles', String.raw`\sin(a\pm b)=\sin a\cos b\pm\cos a\sin b`, `${equation(String.raw`\cos(a\pm b)=\cos a\cos b\mp\sin a\sin b`)}${equation(String.raw`\sin2a=2\sin a\cos a`)}${equation(String.raw`\cos2a=\cos^2a-\sin^2a=1-2\sin^2a`)}Also ${inline(String.raw`\cos2a=2\cos^2a-1`)}. These turn angle combinations into algebra.`),
    row('triangle-laws', 'Sine rule, cosine rule, and triangle area', String.raw`\frac a{\sin A}=\frac b{\sin B}=\frac c{\sin C}`, `${equation(String.raw`c^2=a^2+b^2-2ab\cos C`)}${equation(String.raw`\mathrm{Area}=\frac12ab\sin C`)}Sides ${inline(String.raw`a,b,c`)} face angles ${inline(String.raw`A,B,C`)}. These hold for nondegenerate Euclidean triangles; the cosine rule becomes Pythagoras when ${inline(String.raw`C=\pi/2`)}.`, 'Theorem'),
    row('euler', "Euler's formula", String.raw`e^{i\theta}=\cos\theta+i\sin\theta`, `Here ${inline(String.raw`i^2=-1`)}. Multiplication of unit complex numbers adds angles, explaining the angle-addition identities. At ${inline(String.raw`\theta=\pi`)}, ${inline(String.raw`e^{i\pi}+1=0`)}. A complex number ${inline(String.raw`re^{i\theta}`)} has magnitude ${inline(String.raw`r`)} and argument ${inline(String.raw`\theta`)} modulo ${inline(String.raw`2\pi`)}.`, 'Identity'),
  ] },
  { id: 'calculus', title: 'Calculus: change & accumulation', note: 'Two questions: how fast, and how much?', items: [
    row('limits', 'Limits and continuity', String.raw`f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}h`, `A derivative is the limiting slope, when the limit exists. Continuity at ${inline(String.raw`a`)} means ${inline(String.raw`\lim_{x\to a}f(x)=f(a)`)}. Differentiability implies continuity, not conversely: ${inline(String.raw`|x|`)} is continuous but not differentiable at 0.`, 'Definition'),
    row('derivative-rules', 'Linearity, product, quotient, chain', String.raw`(f\circ g)'(x)=f'(g(x))g'(x)`, `${equation(String.raw`(af+bg)'=af'+bg'`)}${equation(String.raw`(fg)'=f'g+fg'`)}${equation(String.raw`\left(\frac fg\right)'=\frac{f'g-fg'}{g^2}`)}Functions must be differentiable where used, and the quotient requires ${inline(String.raw`g\ne0`)}. Composition multiplies local rates of change.`, 'Rules'),
    row('derivatives', 'Known derivatives', '', table('Derivative reference (angles in radians)', ['Function', 'Derivative', 'Real domain note'], [[inline(String.raw`c`),'0','Constant'],[inline(String.raw`x^r`),inline(String.raw`rx^{r-1}`),'x > 0 for general real r'],[inline(String.raw`e^x`),inline(String.raw`e^x`),'All real x'],[inline(String.raw`a^x`),inline(String.raw`a^x\ln a`),'a > 0'],[inline(String.raw`\ln|x|`),inline(String.raw`1/x`),'x nonzero'],[inline(String.raw`\log_a x`),inline(String.raw`1/(x\ln a)`),'x > 0; a > 0, a not 1'],[inline(String.raw`\sin x`),inline(String.raw`\cos x`),'All real x'],[inline(String.raw`\cos x`),inline(String.raw`-\sin x`),'All real x'],[inline(String.raw`\tan x`),inline(String.raw`\sec^2x`),'cos x nonzero'],[inline(String.raw`\arcsin x`),inline(String.raw`1/\sqrt{1-x^2}`),'|x| < 1'],[inline(String.raw`\arctan x`),inline(String.raw`1/(1+x^2)`),'All real x']]), 'Table'),
    row('integrals', 'Known antiderivatives', '', table('Every row includes an arbitrary constant C', ['Integrand', 'Antiderivative'], [[inline(String.raw`x^r`),inline(String.raw`x^{r+1}/(r+1)+C`)],[inline(String.raw`1/x`),inline(String.raw`\ln|x|+C`)],[inline(String.raw`e^x`),inline(String.raw`e^x+C`)],[inline(String.raw`a^x`),inline(String.raw`a^x/\ln a+C`)],[inline(String.raw`\sin x`),inline(String.raw`-\cos x+C`)],[inline(String.raw`\cos x`),inline(String.raw`\sin x+C`)],[inline(String.raw`\sec^2x`),inline(String.raw`\tan x+C`)],[inline(String.raw`1/(1+x^2)`),inline(String.raw`\arctan x+C`)],[inline(String.raw`1/\sqrt{1-x^2}`),inline(String.raw`\arcsin x+C`)]]) + `The power rule needs ${inline(String.raw`r\ne-1`)}, with ${inline(String.raw`x>0`)} for arbitrary real powers. For ${inline(String.raw`a^x`)}, require ${inline(String.raw`a>0,a\ne1`)}. Work on intervals where the integrand is defined; for the final row ${inline(String.raw`|x|<1`)}. Constants can differ on disconnected intervals.`, 'Table'),
    row('ftc', 'The fundamental theorem of calculus', String.raw`\int_a^b f(x)\,dx=F(b)-F(a)`, `For continuous ${inline(String.raw`f`)} and an antiderivative ${inline(String.raw`F`)} on the interval. Also ${equation(String.raw`\frac d{dx}\int_a^x f(t)\,dt=f(x)`)}Differentiation and integration undo one another under these conditions. Definite integration records signed accumulation, not automatically geometric area.`, 'Theorem'),
    row('integration-methods', 'Substitution and integration by parts', String.raw`\int u\,dv=uv-\int v\,du`, `${equation(String.raw`\int f(g(x))g'(x)\,dx=F(g(x))+C`)}Here ${inline(String.raw`F\prime=f`)}. Substitution reverses the chain rule; integration by parts reverses the product rule. For a definite integral, transform bounds under substitution and include the boundary term in integration by parts.`, 'Rules'),
    row('taylor', 'Taylor expansions and local approximations', String.raw`f(a+h)=f(a)+f'(a)h+\tfrac12f''(a)h^2+\cdots`, `${equation(String.raw`e^x=\sum_{n=0}^{\infty}\frac{x^n}{n!}`)}${equation(String.raw`\sin x=x-\frac{x^3}{3!}+\frac{x^5}{5!}-\cdots`)}${equation(String.raw`\ln(1+x)=x-\frac{x^2}{2}+\frac{x^3}{3}-\cdots`)}The first two series converge for all real ${inline(String.raw`x`)}; the log series converges for ${inline(String.raw`-1<x\le1`)}. A finite Taylor polynomial approximates locally with a remainder; infinitely differentiable does not guarantee equality to the Taylor series.`, 'Theorem'),
    row('gradient', 'Gradient, Jacobian, Hessian', String.raw`df\approx\nabla f(x)^T\,dx`, `For scalar ${inline(String.raw`f:\mathbb R^n\to\mathbb R`)}, the gradient is the vector of first partial derivatives and the Hessian is the matrix of second partials. For ${inline(String.raw`F:\mathbb R^n\to\mathbb R^m`)}, the Jacobian has shape ${inline(String.raw`m\times n`)}.${equation(String.raw`F(x+h)\approx F(x)+J_F(x)h`)}${equation(String.raw`f(x+h)\approx f(x)+\nabla f(x)^Th+\tfrac12h^TH_f(x)h`)}The second-order expansion requires suitable twice differentiability; with continuous second partials the Hessian is symmetric.`, 'Definitions'),
    row('vector-theorems', 'Divergence, curl, and boundary theorems', String.raw`\int_V\nabla\cdot F\,dV=\int_{\partial V}F\cdot n\,dS`, `Divergence measures local outward flux; curl measures local circulation. The divergence theorem equates total divergence to outward boundary flux. Stokes' theorem equates flux of curl to boundary circulation:${equation(String.raw`\int_S(\nabla\times F)\cdot n\,dS=\oint_{\partial S}F\cdot dr`)}Use sufficiently smooth fields and piecewise smooth regions or oriented surfaces with compatible boundary orientation.`, 'Theorems'),
  ] },
  { id: 'linear-algebra', title: 'Linear algebra & optimization', note: 'Many numbers at once, with structure.', items: [
    row('dot', 'Dot products, norms, and projection', String.raw`u^Tv=\|u\|\|v\|\cos\theta`, `${equation(String.raw`\operatorname{proj}_v u=\frac{u^Tv}{v^Tv}v`)}For real Euclidean vectors; projection needs ${inline(String.raw`v\ne0`)}. Orthogonal vectors have zero dot product. Cauchy-Schwarz says ${inline(String.raw`|u^Tv|\le\|u\|\|v\|`)}; it controls how large a correlation can be.`, 'Theorem'),
    row('matrix', 'Matrix products, rank, and inverses', String.raw`(AB)^T=B^TA^T`, `${inline(String.raw`A_{m\times n}B_{n\times p}`)} produces an ${inline(String.raw`m\times p`)} matrix. Generally ${inline(String.raw`AB\ne BA`)}. Rank is the dimension of the column space. A square matrix is invertible exactly when it has full rank, equivalently nonzero determinant. If both are invertible, ${inline(String.raw`(AB)^{-1}=B^{-1}A^{-1}`)}. In computation, solve ${inline(String.raw`Ax=b`)} rather than explicitly forming an inverse.`, 'Rules'),
    row('eigen', 'Eigenvectors and the spectral theorem', String.raw`Av=\lambda v,\qquad v\ne0`, `An eigenvector keeps its direction under the map, up to scaling. A real symmetric matrix has an orthonormal eigenbasis: ${equation(String.raw`A=Q\Lambda Q^T`)}It is positive definite exactly when all eigenvalues are positive. Not every nonsymmetric matrix is diagonalizable.`, 'Theorem'),
    row('svd', 'Singular value decomposition', String.raw`A=U\Sigma V^T`, `Every real ${inline(String.raw`m\times n`)} matrix has an SVD, with orthogonal ${inline(String.raw`U,V`)} and rectangular diagonal ${inline(String.raw`\Sigma`)} containing nonnegative singular values. Keeping the largest ${inline(String.raw`k`)} gives a best rank-at-most-${inline(String.raw`k`)} approximation in Frobenius and spectral norms. This connects least squares, compression, and principal components.`, 'Theorem'),
    row('least-squares', 'Least squares and orthogonality', String.raw`\min_x\|Ax-b\|_2^2`, `${equation(String.raw`A^T(Ax-b)=0`)}The residual is orthogonal to the columns of ${inline(String.raw`A`)}. Full column rank gives a unique solution. QR or SVD is usually numerically preferable to forming ${inline(String.raw`A^TA`)}, which squares the 2-norm condition number when full rank.`, 'Method'),
    row('convex', 'Convexity and stationary points', String.raw`f(tx+(1-t)y)\le tf(x)+(1-t)f(y)`, `For ${inline(String.raw`0\le t\le1`)} on a convex domain. For a differentiable convex function, any point with zero gradient is a global minimum. Strict convexity makes a minimizer unique if it exists. For twice continuously differentiable functions on an open convex domain, a positive semidefinite Hessian everywhere characterizes convexity. A zero gradient alone does not imply a minimum for a nonconvex function.`, 'Definition'),
    row('lagrange', 'Equality constraints and Lagrange multipliers', String.raw`\nabla f(x)=\lambda\nabla g(x)`, `At a constrained local extremum of differentiable ${inline(String.raw`f`)} subject to ${inline(String.raw`g(x)=0`)}, this necessary condition holds when ${inline(String.raw`\nabla g(x)\ne0`)}. It produces candidates, not a guarantee of a minimum. Inequality constraints lead to KKT conditions with additional sign and complementary-slackness requirements.`, 'Method'),
  ] },
  { id: 'probability', title: 'Probability, statistics & beyond', note: 'Reasoning when certainty is not available.', items: [
    row('probability-axioms', 'The probability axioms', String.raw`P(A)\ge0,\qquad P(\Omega)=1`, `${equation(String.raw`P\left(\bigcup_i A_i\right)=\sum_i P(A_i)`)}The final rule is countable additivity for pairwise disjoint events. It implies ${inline(String.raw`P(A^c)=1-P(A)`)} and ${inline(String.raw`P(A\cup B)=P(A)+P(B)-P(A\cap B)`)}. Mutually exclusive is not the same as independent.`, 'Axioms'),
    row('bayes', 'Conditional probability and Bayes', String.raw`P(A\mid B)=\frac{P(B\mid A)P(A)}{P(B)}`, `Require ${inline(String.raw`P(B)>0`)}; the displayed conditional on ${inline(String.raw`A`)} also needs ${inline(String.raw`P(A)>0`)}. More generally ${inline(String.raw`P(A\mid B)=P(A\cap B)/P(B)`)}. Independent events satisfy ${inline(String.raw`P(A\cap B)=P(A)P(B)`)}. Update prior odds with evidence, but keep base rates in the calculation.`, 'Theorem'),
    row('counting', 'Permutations, combinations, and factorials', String.raw`{}^nP_k=\frac{n!}{(n-k)!},\qquad\binom nk=\frac{n!}{k!(n-k)!}`, `For integers ${inline(String.raw`0\le k\le n`)}, with ${inline(String.raw`0!=1`)}. Permutations count ordered choices without replacement; combinations ignore order. With replacement and order, ${inline(String.raw`k`)} draws from ${inline(String.raw`n`)} choices give ${inline(String.raw`n^k`)} sequences.`, 'Formulas'),
    row('expectation', 'Expectation, variance, and covariance', String.raw`E[aX+bY]=aE[X]+bE[Y]`, `Linearity of expectation needs no independence, assuming the expectations exist.${equation(String.raw`\operatorname{Var}(X)=E[X^2]-E[X]^2`)}${equation(String.raw`\operatorname{Var}(X+Y)=\operatorname{Var}(X)+\operatorname{Var}(Y)+2\operatorname{Cov}(X,Y)`)}These variance formulas require finite second moments. Independence implies zero covariance, but the converse generally fails.`),
    row('distributions', 'Three distributions to recognize', '', table('Common distributions', ['Distribution', 'Mean', 'Variance'], [['Bernoulli(p)',inline(String.raw`p`),inline(String.raw`p(1-p)`)],['Binomial(n,p)',inline(String.raw`np`),inline(String.raw`np(1-p)`)],['Normal(mu, sigma squared)',inline(String.raw`\mu`),inline(String.raw`\sigma^2`)]]) + 'Bernoulli models one yes/no outcome; binomial counts successes in n independent trials with common probability p. A normal distribution describes a symmetric continuous bell curve, not every real dataset.', 'Table'),
    row('lln-clt', 'Law of large numbers and central limit theorem', String.raw`\frac{\sqrt n(\overline X_n-\mu)}{\sigma}\ \Rightarrow\ N(0,1)`, `For independent identically distributed variables with finite mean and finite positive variance, the classical CLT gives this convergence in distribution. The law of large numbers says the sample mean approaches the population mean; it is a different claim. Neither removes bias from a badly sampled dataset.`, 'Theorems'),
    row('inference', 'Standard error, intervals, and p-values', String.raw`\operatorname{SE}(\overline X)=\frac{\sigma}{\sqrt n}`, `For independent observations with common variance. Estimate with ${inline(String.raw`s/\sqrt n`)} when appropriate. A 95% confidence procedure covers the fixed true parameter in 95% of repeated samples under its assumptions; it is not a 95% posterior probability. A p-value is the null-model probability of a statistic at least as extreme as observed, not the probability that the null is true.`, 'Interpretation'),
    row('entropy', 'Entropy and cross entropy', String.raw`H(p)=-\sum_i p_i\log p_i`, `${equation(String.raw`H(p,q)=-\sum_i p_i\log q_i`)}${equation(String.raw`D_{\mathrm{KL}}(p\|q)=H(p,q)-H(p)\ge0`)}For discrete distributions. Use ${inline(String.raw`0\log0=0`)} by continuity. If ${inline(String.raw`p_i>0`)} but ${inline(String.raw`q_i=0`)}, cross entropy and KL divergence are infinite. Natural logs give nats; base-two logs give bits.`, 'Definition'),
    row('fourier', 'Fourier: decomposing a signal into frequencies', String.raw`\widehat f(\omega)=\int_{-\infty}^{\infty}f(t)e^{-i\omega t}\,dt`, `One common convention; other normalizations exist. For absolutely integrable ${inline(String.raw`f`)} this transform is defined; inversion needs additional conditions. Linearity and the convolution theorem turn combinations of signals into algebra. Trigonometry, complex numbers, and linear algebra meet here.`, 'Connection'),
    row('compactness', 'Compactness and existence of extrema', '', 'In finite-dimensional Euclidean space, a set is compact exactly when it is closed and bounded. A continuous real-valued function on a nonempty compact set attains a maximum and a minimum. Closed and bounded is not enough for compactness in general infinite-dimensional normed spaces. Conditions are part of the theorem, not fine print.', 'Theorem'),
  ] },
];

export function renderReference() {
  const count = sections.reduce((total, section) => total + section.items.length, 0);
  return `<div class="foundations">
    <header class="foundation-intro"><p class="foundation-eyebrow">01 / A return to mathematics</p><h2>Mathematical Foundations</h2><p>Perhaps you remember the pleasure of a proof clicking into place, or a pattern appearing where you least expected it. Life may have taken you elsewhere. The mathematics is still here.</p><p class="foundation-dedication">For the part of you that always wanted to know why.</p></header>
    <div class="foundation-tools"><label class="foundation-search"><span data-foundation-icon="search"></span><input type="search" aria-label="Search mathematical reminders" placeholder="Search mathematics" autocomplete="off"></label><span class="foundation-count" role="status" aria-live="polite">${count} reminders</span><button type="button" data-collapse title="Collapse all reminders" aria-label="Collapse all reminders"><span data-foundation-icon="collapse"></span></button></div>
    <label class="foundation-topic-picker">Topic <select aria-label="Jump to topic"><option value="">All topics</option>${sections.map(section => `<option value="${section.id}">${section.title}</option>`).join('')}</select></label>
    <div class="foundation-layout"><nav class="foundation-nav" aria-label="Foundation topics">${sections.map(section => `<a href="#${section.id}">${section.title}</a>`).join('')}</nav><div class="foundation-content"><p class="foundation-scope">A selective memory map, from school arithmetic to ideas you meet in graduate study. Identities invite recall; assumptions and examples invite understanding.</p><p class="foundation-empty" hidden>No matching reminders.</p>${sections.map((section, sectionIndex) => `<section id="${section.id}" class="foundation-section"><header><span>${String(sectionIndex + 1).padStart(2, '0')}</span><div><h3>${section.title}</h3><p>${section.note}</p></div></header><ul class="foundation-list">${section.items.map(item => `<li><details id="${item.id}"><summary><span class="foundation-item-heading"><span>${item.title}</span><small>${item.kind}</small></span>${item.formula ? equation(item.formula) : ''}</summary><div class="foundation-detail">${item.detail}</div></details></li>`).join('')}</ul></section>`).join('')}</div></div>
  </div>`;
}