= Finding the Optimal Vocabulary for Neural Machine Translation

:author: Thamme Gowda <tg@isi.edu>
//; Jonathan May <jonmay@isi.edu>
:date: 2020-11-1 10:20
// :modified: 2020-12-04 18:40
:tags: NMT, Published
:category: Publication
:template: article
:slug: 2020-optimal-vocab-nmt
:icons: font
:summary: Finding the Optimal Vocabulary for Neural Machine Translation
:description: We cast neural machine translation (NMT) as a classification task in an autoregressive setting and analyze the limitations of both classification and autoregression components. \
Classifiers are known to perform better with balanced class distributions during training. \
Since the Zipfian nature of languages causes imbalanced classes, we explore its effect on NMT. \
We analyze the effect of various vocabulary sizes on NMT performance on multiple languages with many data sizes, and reveal an explanation for _why_ certain vocabulary sizes are better than others.


== Abstract

We cast neural machine translation (NMT) as a classification task in an autoregressive setting and analyze the limitations of both classification and autoregression components.
Classifiers are known to perform better with balanced class distributions during training.
Since the Zipfian nature of languages causes imbalanced classes, we explore its effect on NMT.
We analyze the effect of various vocabulary sizes on NMT performance on multiple languages with many data sizes, and reveal an explanation for _why_ certain vocabulary sizes are better than others.

== Links

* DOI http://dx.doi.org/10.18653/v1/2020.findings-emnlp.352[10.18653/v1/2020.findings-emnlp.352^]
* PDF https://www.aclweb.org/anthology/2020.findings-emnlp.352.pdf[icon:download[2x,role=red]^]
* Code https://github.com/thammegowda/005-nmt-imbalance +
 The github repository contains scripts to download data and reproduce experiments, as well as system outputs and our analysis reported in this paper.


==  Citation
+
[bibtex]
----
@inproceedings{gowda-may-2020-finding,
    title = "Finding the Optimal Vocabulary Size for Neural Machine Translation",
    author = "Gowda, Thamme  and
      May, Jonathan",
    booktitle = "Findings of the Association for Computational Linguistics: EMNLP 2020",
    month = nov,
    year = "2020",
    address = "Online",
    publisher = "Association for Computational Linguistics",
    url = "https://www.aclweb.org/anthology/2020.findings-emnlp.352",
    doi = "10.18653/v1/2020.findings-emnlp.352",
    pages = "3955--3964",
}

----

+++ <details><summary> +++
*Acknowledgements*:
+++ </summary><div> +++

[.small]#This research is based upon work supported in part by the Office of the Director of National Intelligence (ODNI),
Intelligence Advanced Research Projects Activity (IARPA),  via contract # FA8650-17-C-9116,
and by research sponsored by Air Force Research Laboratory (AFRL) under agreement number FA8750-19-1-1000.
The views and conclusions contained herein are those of the authors and should not be interpreted as
necessarily representing the official policies, either expressed or implied, of ODNI, IARPA, Air Force Laboratory, DARPA, or the U.S. Government.
The U.S. Government is authorized to reproduce and distribute reprints for governmental purposes notwithstanding any copyright annotation therein.#
+++ </div></details> +++